/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade.ap2;

import static atividade.ap2.MainScreen.binaryScreen;
import javax.swing.JOptionPane;

/**
 *
 * @author Deivid
 */
public class BinaryScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form BinaryScreen
     */
    public BinaryScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOrdem = new javax.swing.JButton();
        jButtonPosOrdem = new javax.swing.JButton();
        jButtonPreordem = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButtonOrdem.setText("Ordem");
        jButtonOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdemActionPerformed(evt);
            }
        });

        jButtonPosOrdem.setText("Pos Ordem");
        jButtonPosOrdem.setMaximumSize(new java.awt.Dimension(71, 25));
        jButtonPosOrdem.setMinimumSize(new java.awt.Dimension(71, 25));
        jButtonPosOrdem.setPreferredSize(new java.awt.Dimension(71, 25));
        jButtonPosOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosOrdemActionPerformed(evt);
            }
        });

        jButtonPreordem.setText("Pre Ordem");
        jButtonPreordem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreordemActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Escolha o metodo de visualização");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPosOrdem, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPreordem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOrdem)
                    .addComponent(jButtonPosOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPreordem))
                .addGap(18, 18, 18)
                .addComponent(jButtonSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        binaryScreen.setVisible(false);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,Arvore.ordem(Arvore.raiz));
    }//GEN-LAST:event_jButtonOrdemActionPerformed

    private void jButtonPosOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosOrdemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,Arvore.posordem(Arvore.raiz));
    }//GEN-LAST:event_jButtonPosOrdemActionPerformed

    private void jButtonPreordemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreordemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,Arvore.preordem(Arvore.raiz));
    }//GEN-LAST:event_jButtonPreordemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOrdem;
    private javax.swing.JButton jButtonPosOrdem;
    private javax.swing.JButton jButtonPreordem;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
