/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade.ap2;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Deivid
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    public static BinaryCreationScreen binaryCreationScreen;
    public static BinaryScreen binaryScreen;
    public static DepthScreen depthScreen;
    public static BetterRouteScreen betterRouteScreen;
    
    public MainScreen() {
        initComponents();
    }
    
    public static void setTelaInterna(JInternalFrame t){
        jDesktopPane1.add(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBinaria = new javax.swing.JMenu();
        jMenuItemCriar = new javax.swing.JMenuItem();
        jMenuItemVisualizar = new javax.swing.JMenuItem();
        jMenuItemBuscaP = new javax.swing.JMenuItem();
        jMenuItemBuscaN = new javax.swing.JMenuItem();
        jMenuDijkstra = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        jMenuBinaria.setText("Arvore Binaria");
        jMenuBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBinariaActionPerformed(evt);
            }
        });

        jMenuItemCriar.setText("Criar");
        jMenuItemCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarActionPerformed(evt);
            }
        });
        jMenuBinaria.add(jMenuItemCriar);

        jMenuItemVisualizar.setText("Visualizar");
        jMenuItemVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarActionPerformed(evt);
            }
        });
        jMenuBinaria.add(jMenuItemVisualizar);

        jMenuItemBuscaP.setText("Busca Profundidade");
        jMenuItemBuscaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscaPActionPerformed(evt);
            }
        });
        jMenuBinaria.add(jMenuItemBuscaP);

        jMenuItemBuscaN.setText("Busca Nivel");
        jMenuBinaria.add(jMenuItemBuscaN);

        jMenuBar1.add(jMenuBinaria);

        jMenuDijkstra.setText("Dijkstra");

        jMenuItem6.setText("Buscar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuDijkstra.add(jMenuItem6);

        jMenuBar1.add(jMenuDijkstra);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarActionPerformed
        // TODO add your handling code here:
        if(binaryCreationScreen == null){
            
            binaryCreationScreen = new BinaryCreationScreen();          
        }
        if(binaryCreationScreen != null){
            if(!binaryCreationScreen.isVisible()){
                MainScreen.setTelaInterna(binaryCreationScreen);
                binaryCreationScreen.setVisible(true); 
            }
            binaryCreationScreen.toFront();
        }
    }//GEN-LAST:event_jMenuItemCriarActionPerformed

    private void jMenuBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBinariaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuBinariaActionPerformed

    private void jMenuItemVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarActionPerformed
        // TODO add your handling code here:
        if(binaryScreen == null){
            
            binaryScreen = new BinaryScreen();          
        }
        if(binaryScreen != null){
            if(!binaryScreen.isVisible()){
                MainScreen.setTelaInterna(binaryScreen);
                binaryScreen.setVisible(true); 
            }
            binaryScreen.toFront();
        }
    }//GEN-LAST:event_jMenuItemVisualizarActionPerformed

    private void jMenuItemBuscaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscaPActionPerformed
        // TODO add your handling code here:
        if(depthScreen == null){
            
            depthScreen = new DepthScreen();          
        }
        if(depthScreen != null){
            if(!depthScreen.isVisible()){
                MainScreen.setTelaInterna(depthScreen);
                depthScreen.setVisible(true); 
            }
            depthScreen.toFront();
        }
    }//GEN-LAST:event_jMenuItemBuscaPActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        if(betterRouteScreen == null){
            
            betterRouteScreen = new BetterRouteScreen();          
        }
        if(betterRouteScreen != null){
            if(!betterRouteScreen.isVisible()){
                MainScreen.setTelaInterna(betterRouteScreen);
                betterRouteScreen.setVisible(true); 
            }
            betterRouteScreen.toFront();
        }        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBinaria;
    private javax.swing.JMenu jMenuDijkstra;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemBuscaN;
    private javax.swing.JMenuItem jMenuItemBuscaP;
    private javax.swing.JMenuItem jMenuItemCriar;
    private javax.swing.JMenuItem jMenuItemVisualizar;
    // End of variables declaration//GEN-END:variables
}
